name: pr

on:

  pull_request:


jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4
      - run: pipx install poetry

      - uses: actions/setup-python@v5
        with:
          python-version: '3.8'
          cache: "poetry"

      - run: poetry install

      - name: build
        run: make build
