site_name: Poetry Docker
site_description: Poetry plugin for creating docker images.

nav:
    - Home: index.md
    - Release Notes:
        - 0.5.1: release_notes/0.5.1.md
        - 0.5.0: release_notes/0.5.0.md
        - 0.4.0: release_notes/0.4.0.md
